









<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"帖子类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryForum"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基金类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJijin"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基金管理",
                        "menuJump":"列表",
                        "tableName":"jijin"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基金净值管理",
                        "menuJump":"列表",
                        "tableName":"jingzhi"
                    }
                    ,{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"基金自选管理",
                        "menuJump":"列表",
                        "tableName":"jijinCollection"
                    }
                ],
                "menu":"基金管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"持有基金管理",
                        "menuJump":"列表",
                        "tableName":"jijinChiyou"
                    }
					,{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"交易记录管理",
                        "menuJump":"列表",
                        "tableName":"jiaoyijilu"
                    }
                ],
                "menu":"持有基金管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"基金管理",
                        "menuJump":"列表",
                        "tableName":"jijin"
                    }
					,{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"基金净值管理",
                        "menuJump":"列表",
                        "tableName":"jingzhi"
                    }
                    ,{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"基金自选管理",
                        "menuJump":"列表",
                        "tableName":"jijinCollection"
                    }
                ],
                "menu":"基金管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"持有基金管理",
                        "menuJump":"列表",
                        "tableName":"jijinChiyou"
                    }
					,{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"交易记录管理",
                        "menuJump":"列表",
                        "tableName":"jiaoyijilu"
                    }
                ],
                "menu":"持有基金管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
